apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: space-arcaders
data:
  config : |
    server {
      index index.html;
      error_log  /var/log/nginx/error.log;
      access_log /var/log/nginx/access.log;
      root /data;

      location / {
          try_files $uri $uri/ /index.php?$query_string;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: space-arcaders
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: data
        hostPath:
          path: /mnt/office/space-arcaders
      - name: config
        configMap:
          name: nginx-config
          items:
          - key: config
            path: site.conf
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: data
          mountPath: /data
        - name: config
          mountPath: /etc/nginx/conf.d
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: space-arcaders
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: space-arcaders
  namespace: space-arcaders
  annotations:
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  tls:
    - hosts:
        - spacearcaders.co.uk
      secretName: space-arcaders-tls
  rules:
  - host: spacearcaders.co.uk
    http: &http
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80

