apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: windows
spec:
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
---
apiVersion: v1
kind: Endpoints
metadata:
  namespace: default
  name: windows
subsets:
  - addresses:
      - ip: 10.1.0.1
    ports:
      - port: 80
        name: http
      - port: 443
        name: https
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: windows-forward
  namespace: default
  annotations:
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  tls:
    - hosts:
        - adfs.cardifftec.uk
      secretName: windows-forward-tls
  rules:
  - host: adfs.cardifftec.uk
    http: &http
      paths:
      - path: /
        backend:
          serviceName: windows
          servicePort: 443
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: windows-rdg
  namespace: default
  annotations:
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  tls:
    - hosts:
        - server.wewillfixyourpc.co.uk
      secretName: windows-rdg-tls
  rules:
  - host: server.wewillfixyourpc.co.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: windows
          servicePort: 80
